services:
  mylabvault:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: mylabvault
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./app/data:/app/data
    networks:
      - mylabvault-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mylabvault-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"